# Generated by Django 3.0.5 on 2020-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200417_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
