# Generated by Django 3.0.5 on 2020-04-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_statistic', to='articles.Article')),
            ],
        ),
    ]
