# Generated by Django 3.0.5 on 2020-04-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
