# Generated by Django 3.0.5 on 2020-05-01 13:24

import datetime
from django.db import migrations
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default=datetime.datetime(2020, 5, 1, 13, 24, 26, 12360, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
