# Generated by Django 3.0.5 on 2020-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200420_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='article-photos/'),
        ),
    ]
